version: '3.1'

services:
         
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./db_data:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d/:ro
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=fimadmin
        container_name: db

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080
        container_name: admin
